name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
          cache: true
      - name: go vet
        run: go vet ./...
      - name: go build
        run: go build ./...
      - name: go test (race + cover)
        run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
          cache: true
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
